<?php
function my_crud_menu(){
    $item['my_crud'] = [
        'title' => 'List Records',
        'description' => '',
        'route' => 'my_crud.mycrud_controller_listing'
    ];

    $item['my_crud/form/data'] = [
        'title' => 'Add / Edit Form',
        'description' => '',
        'route' => 'my_crud.mycrud_form'
    ];

    $item['my_crud/form/delete/{cid}'] = [
        'title' => 'Delete Records',
        'description' => '',
        'route' => 'my_crud.delete_form'
    ];

    return $item;
}
?>